# Main entry point for the role.

---

- name: "Main | Include role initialization tasks"
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/init.yml"
    apply:
      tags:
        - "always"
        - "quadlet_podman_always"
  tags:
    - "always"
    - "quadlet_podman_always"


- name: "Main | Include setup tasks (install): best platform matches (if any), then default"
  ansible.builtin.include_tasks:
    file: "{{ __quadlet_podman_task_file }}"
    apply:
      tags:
        - "quadlet_podman_setup"
  vars:
    __quadlet_podman_task_file: "{{ role_path }}/tasks/setup/install/{{ __quadlet_podman_loop_item }}"
  when:
    - quadlet_podman_state == 'present'
    - __quadlet_podman_task_file is ansible.builtin.file
  loop: "{{ __quadlet_podman_platform_filenames_most_specific_first + ['default.yml'] }}"
  loop_control:
    loop_var: "__quadlet_podman_loop_item"
  tags:
    - "quadlet_podman_setup"


- name: "Main | Include configuration tasks: best platform matches (if any), then default"
  ansible.builtin.include_tasks:
    file: "{{ __quadlet_podman_task_file }}"
    apply:
      tags:
        - "quadlet_podman_config"
  vars:
    __quadlet_podman_task_file: "{{ role_path }}/tasks/config/{{ __quadlet_podman_loop_item }}"
  when:
    - quadlet_podman_state == 'present'
    - __quadlet_podman_task_file is ansible.builtin.file
  loop: "{{ __quadlet_podman_platform_filenames_most_specific_first + ['default.yml'] }}"
  loop_control:
    loop_var: "__quadlet_podman_loop_item"
  tags:
    - "quadlet_podman_config"


- name: "Main | Include service or daemon management tasks: best platform matches (if any), then default"
  ansible.builtin.include_tasks:
    file: "{{ __quadlet_podman_task_file }}"
    apply:
      tags:
        - "quadlet_podman_service"
  vars:
    __quadlet_podman_task_file: "{{ role_path }}/tasks/service/{{ __quadlet_podman_loop_item }}"
  when:
    - quadlet_podman_state == 'present'
    - __quadlet_podman_task_file is ansible.builtin.file
  loop: "{{ __quadlet_podman_platform_filenames_most_specific_first + ['default.yml'] }}"
  loop_control:
    loop_var: "__quadlet_podman_loop_item"
  tags:
    - "quadlet_podman_service"


- name: "Main | Include setup tasks (uninstall): best platform matches (if any), then default"
  ansible.builtin.include_tasks:
    file: "{{ __quadlet_podman_task_file }}"
    apply:
      tags:
        - "quadlet_podman_setup"
  vars:
    __quadlet_podman_task_file: "{{ role_path }}/tasks/setup/uninstall/{{ __quadlet_podman_loop_item }}"
  when:
    - quadlet_podman_state == 'absent'
    - __quadlet_podman_task_file is ansible.builtin.file
  loop: "{{ __quadlet_podman_platform_filenames_most_specific_first + ['default.yml'] }}"
  loop_control:
    loop_var: "__quadlet_podman_loop_item"
  tags:
    - "quadlet_podman_setup"
